[2024-06-15T05:04:34.727+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-15T05:04:34.775+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.data_processing manual__2024-06-14T23:33:15.612989+00:00 [queued]>
[2024-06-15T05:04:34.785+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.data_processing manual__2024-06-14T23:33:15.612989+00:00 [queued]>
[2024-06-15T05:04:34.786+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-06-15T05:04:34.830+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): data_processing> on 2024-06-14 23:33:15.612989+00:00
[2024-06-15T05:04:34.835+0530] {standard_task_runner.py:63} INFO - Started process 38761 to run task
[2024-06-15T05:04:34.840+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'data_processing', 'manual__2024-06-14T23:33:15.612989+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpx4zc0c7m']
[2024-06-15T05:04:34.842+0530] {standard_task_runner.py:91} INFO - Job 128: Subtask data_processing
[2024-06-15T05:04:34.915+0530] {task_command.py:426} INFO - Running <TaskInstance: my_data_pipeline_dag.data_processing manual__2024-06-14T23:33:15.612989+00:00 [running]> on host DESKTOP-J05K55U.
[2024-06-15T05:04:35.050+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='data_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T23:33:15.612989+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T23:33:15.612989+00:00'
[2024-06-15T05:04:35.052+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-15T05:04:35.053+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-15T05:04:35.055+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python "/home/wsl/airflow/dags/Collect Data/data_processing.py"']
[2024-06-15T05:04:35.067+0530] {subprocess.py:86} INFO - Output:
[2024-06-15T05:04:50.953+0530] {subprocess.py:93} INFO - 24/06/15 05:04:50 WARN Utils: Your hostname, DESKTOP-J05K55U resolves to a loopback address: 127.0.1.1; using 172.31.56.255 instead (on interface eth0)
[2024-06-15T05:04:51.023+0530] {subprocess.py:93} INFO - 24/06/15 05:04:50 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-06-15T05:04:55.706+0530] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-06-15T05:04:55.707+0530] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-06-15T05:04:56.331+0530] {subprocess.py:93} INFO - 24/06/15 05:04:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-06-15T05:18:02.360+0530] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 1][Stage 0:>                                                          (0 + 1) / 1]                                                                                [Stage 1:>                                                          (0 + 1) / 1]                                                                                24/06/15 05:18:02 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-15T05:18:02.435+0530] {subprocess.py:93} INFO - 24/06/15 05:18:02 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-15T05:18:02.465+0530] {subprocess.py:93} INFO - 24/06/15 05:18:02 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-15T05:20:17.197+0530] {subprocess.py:93} INFO - [Stage 3:>                                                          (0 + 3) / 3][Stage 3:>                                                          (0 + 3) / 3][Stage 3:>                                                          (0 + 3) / 3][Stage 3:===================>                                       (1 + 2) / 3][Stage 3:=======================================>                   (2 + 1) / 3]24/06/15 05:20:17 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-15T05:20:17.201+0530] {subprocess.py:93} INFO - 24/06/15 05:20:17 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2024-06-15T05:20:26.053+0530] {subprocess.py:93} INFO - [Stage 5:>                                                          (0 + 1) / 1]                                                                                <pyspark.sql.session.SparkSession object at 0x7efe94541cf0>
[2024-06-15T05:20:26.094+0530] {subprocess.py:93} INFO - Data saved successfully as Parquet file at /home/wsl/airflow/dags/Collect Data/world.parquet
[2024-06-15T05:20:29.971+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-15T05:20:29.988+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-15T05:20:35.022+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in xcom_push
    XCom.set(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 257, in set
    session.execute(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: DELETE FROM xcom WHERE xcom."key" = ? AND xcom.run_id = ? AND xcom.task_id = ? AND xcom.dag_id = ? AND xcom.map_index = ?]
[parameters: ('return_value', 'manual__2024-06-14T23:33:15.612989+00:00', 'data_processing', 'my_data_pipeline_dag', -1)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-06-15T05:20:35.072+0530] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=my_data_pipeline_dag, task_id=data_processing, execution_date=20240614T233315, start_date=20240614T233434, end_date=20240614T235035
[2024-06-15T05:20:40.108+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 128 for task data_processing ((sqlite3.OperationalError) database is locked
[SQL: INSERT INTO log (dttm, dag_id, task_id, map_index, event, execution_date, run_id, owner, owner_display_name, extra) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2024-06-14 23:50:35.071179', 'my_data_pipeline_dag', 'data_processing', -1, 'failed', '2024-06-14 23:33:15.612989', 'manual__2024-06-14T23:33:15.612989+00:00', 'airflow', None, None)]
(Background on this error at: https://sqlalche.me/e/14/e3q8); 38761)
