[2024-05-28T20:14:52.551+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T20:14:52.580+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T14:22:52.983196+00:00 [queued]>
[2024-05-28T20:14:52.592+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T14:22:52.983196+00:00 [queued]>
[2024-05-28T20:14:52.593+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-28T20:14:52.611+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collect_data_1> on 2024-05-28 14:22:52.983196+00:00
[2024-05-28T20:14:52.615+0530] {standard_task_runner.py:63} INFO - Started process 226096 to run task
[2024-05-28T20:14:52.620+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'collect_data_1', 'manual__2024-05-28T14:22:52.983196+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpwovgzu8o']
[2024-05-28T20:14:52.621+0530] {standard_task_runner.py:91} INFO - Job 32: Subtask collect_data_1
[2024-05-28T20:14:52.668+0530] {task_command.py:426} INFO - Running <TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T14:22:52.983196+00:00 [running]> on host DESKTOP-J05K55U.
[2024-05-28T20:14:52.760+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_data_1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T14:22:52.983196+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T14:22:52.983196+00:00'
[2024-05-28T20:14:52.761+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T20:14:52.761+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-28T20:14:52.762+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'C:/Users/user/Desktop/Python/Airflow/covid_19_europe.py']
[2024-05-28T20:14:52.768+0530] {subprocess.py:86} INFO - Output:
[2024-05-28T20:14:52.770+0530] {subprocess.py:93} INFO - /usr/bin/bash: line 1: C:/Users/user/Desktop/Python/Airflow/covid_19_europe.py: No such file or directory
[2024-05-28T20:14:52.770+0530] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-28T20:14:52.771+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T20:14:52.779+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-28T20:14:52.782+0530] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=my_data_pipeline_dag, task_id=collect_data_1, execution_date=20240528T142252, start_date=20240528T144452, end_date=20240528T144452
[2024-05-28T20:14:52.797+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task collect_data_1 (Bash command failed. The command returned a non-zero exit code 127.; 226096)
[2024-05-28T20:14:52.834+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T20:14:52.854+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T20:14:52.855+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
