[2024-05-28T20:50:43.287+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T20:50:43.310+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_2 manual__2024-05-28T15:20:30.235659+00:00 [queued]>
[2024-05-28T20:50:43.317+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_2 manual__2024-05-28T15:20:30.235659+00:00 [queued]>
[2024-05-28T20:50:43.318+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-28T20:50:43.337+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collect_data_2> on 2024-05-28 15:20:30.235659+00:00
[2024-05-28T20:50:43.340+0530] {standard_task_runner.py:63} INFO - Started process 243136 to run task
[2024-05-28T20:50:43.361+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'collect_data_2', 'manual__2024-05-28T15:20:30.235659+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp42u93r8m']
[2024-05-28T20:50:43.362+0530] {standard_task_runner.py:91} INFO - Job 44: Subtask collect_data_2
[2024-05-28T20:50:43.407+0530] {task_command.py:426} INFO - Running <TaskInstance: my_data_pipeline_dag.collect_data_2 manual__2024-05-28T15:20:30.235659+00:00 [running]> on host DESKTOP-J05K55U.
[2024-05-28T20:50:43.565+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_data_2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T15:20:30.235659+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T15:20:30.235659+00:00'
[2024-05-28T20:50:43.578+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T20:50:43.579+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-28T20:50:43.581+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python "/home/wsl/airflow/dags/Collect data/covid_19_usa.py"']
[2024-05-28T20:50:43.591+0530] {subprocess.py:86} INFO - Output:
[2024-05-28T20:50:43.612+0530] {subprocess.py:93} INFO - python: can't open file '/home/wsl/airflow/dags/Collect data/covid_19_usa.py': [Errno 2] No such file or directory
[2024-05-28T20:50:43.618+0530] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-28T20:50:43.620+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T20:50:43.639+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-28T20:50:43.645+0530] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=my_data_pipeline_dag, task_id=collect_data_2, execution_date=20240528T152030, start_date=20240528T152043, end_date=20240528T152043
[2024-05-28T20:50:43.668+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task collect_data_2 (Bash command failed. The command returned a non-zero exit code 2.; 243136)
[2024-05-28T20:50:43.677+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T20:50:43.710+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T20:50:43.712+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
