[2024-05-28T20:47:09.355+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T20:47:09.414+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T15:12:00.734009+00:00 [queued]>
[2024-05-28T20:47:09.425+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T15:12:00.734009+00:00 [queued]>
[2024-05-28T20:47:09.426+0530] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-28T20:47:09.457+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): collect_data_1> on 2024-05-28 15:12:00.734009+00:00
[2024-05-28T20:47:09.466+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_data_pipeline_dag', 'collect_data_1', 'manual__2024-05-28T15:12:00.734009+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpkyyfg2mh']
[2024-05-28T20:47:09.468+0530] {standard_task_runner.py:91} INFO - Job 42: Subtask collect_data_1
[2024-05-28T20:47:09.466+0530] {standard_task_runner.py:63} INFO - Started process 241244 to run task
[2024-05-28T20:47:09.569+0530] {task_command.py:426} INFO - Running <TaskInstance: my_data_pipeline_dag.collect_data_1 manual__2024-05-28T15:12:00.734009+00:00 [running]> on host DESKTOP-J05K55U.
[2024-05-28T20:47:10.298+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_data_1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T15:12:00.734009+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T15:12:00.734009+00:00'
[2024-05-28T20:47:10.306+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T20:47:10.308+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-28T20:47:10.314+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python Collect data/covid_19_europe.py']
[2024-05-28T20:47:10.321+0530] {subprocess.py:86} INFO - Output:
[2024-05-28T20:47:10.337+0530] {subprocess.py:93} INFO - python: can't open file '/tmp/airflowtmp0e2drdze/Collect': [Errno 2] No such file or directory
[2024-05-28T20:47:10.339+0530] {subprocess.py:97} INFO - Command exited with return code 2
[2024-05-28T20:47:10.341+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T20:47:10.353+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wsl/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-05-28T20:47:10.367+0530] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=my_data_pipeline_dag, task_id=collect_data_1, execution_date=20240528T151200, start_date=20240528T151709, end_date=20240528T151710
[2024-05-28T20:47:10.392+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task collect_data_1 (Bash command failed. The command returned a non-zero exit code 2.; 241244)
[2024-05-28T20:47:10.422+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T20:47:10.446+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T20:47:10.458+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
